module.exports = {
  "packages/accordion/stories/accordion.stories":
    "/Users/morse/Documents/GitHub/chakra-ui/packages/accordion/stories/accordion.stories.tsx",
  "packages/alert/stories/alert.stories":
    "/Users/morse/Documents/GitHub/chakra-ui/packages/alert/stories/alert.stories.tsx",
  "packages/alert-dialog/stories/alert-dialog.stories":
    "/Users/morse/Documents/GitHub/chakra-ui/packages/alert-dialog/stories/alert-dialog.stories.tsx",
  "packages/avatar/stories/avatar.stories":
    "/Users/morse/Documents/GitHub/chakra-ui/packages/avatar/stories/avatar.stories.tsx",
  "packages/breadcrumb/stories/breadcrumb.stories":
    "/Users/morse/Documents/GitHub/chakra-ui/packages/breadcrumb/stories/breadcrumb.stories.tsx",
  "packages/button/stories/button.stories":
    "/Users/morse/Documents/GitHub/chakra-ui/packages/button/stories/button.stories.tsx",
  "packages/checkbox/stories/checkbox.stories":
    "/Users/morse/Documents/GitHub/chakra-ui/packages/checkbox/stories/checkbox.stories.tsx",
  "packages/clickable/stories/use-clickable.stories":
    "/Users/morse/Documents/GitHub/chakra-ui/packages/clickable/stories/use-clickable.stories.tsx",
  "packages/close-button/stories/close-button.stories":
    "/Users/morse/Documents/GitHub/chakra-ui/packages/close-button/stories/close-button.stories.tsx",
  "packages/collapse/stories/collapse.stories":
    "/Users/morse/Documents/GitHub/chakra-ui/packages/collapse/stories/collapse.stories.tsx",
  "packages/color-mode/stories/color-mode.stories":
    "/Users/morse/Documents/GitHub/chakra-ui/packages/color-mode/stories/color-mode.stories.tsx",
  "packages/counter/stories/use-counter.stories":
    "/Users/morse/Documents/GitHub/chakra-ui/packages/counter/stories/use-counter.stories.tsx",
  "packages/css/stories/css.stories":
    "/Users/morse/Documents/GitHub/chakra-ui/packages/css/stories/css.stories.tsx",
  "packages/descendant/stories/use-descendant.stories":
    "/Users/morse/Documents/GitHub/chakra-ui/packages/descendant/stories/use-descendant.stories.tsx",
  "packages/drawer/stories/drawer.stories":
    "/Users/morse/Documents/GitHub/chakra-ui/packages/drawer/stories/drawer.stories.tsx",
  "packages/editable/stories/editable.stories":
    "/Users/morse/Documents/GitHub/chakra-ui/packages/editable/stories/editable.stories.tsx",
  "packages/form-control/stories/form-control.stories":
    "/Users/morse/Documents/GitHub/chakra-ui/packages/form-control/stories/form-control.stories.tsx",
  "packages/icon/stories/icon.stories":
    "/Users/morse/Documents/GitHub/chakra-ui/packages/icon/stories/icon.stories.tsx",
  "packages/icons/src/icons.stories":
    "/Users/morse/Documents/GitHub/chakra-ui/packages/icons/src/icons.stories.tsx",
  "packages/image/stories/image.stories":
    "/Users/morse/Documents/GitHub/chakra-ui/packages/image/stories/image.stories.tsx",
  "packages/input/stories/input.stories":
    "/Users/morse/Documents/GitHub/chakra-ui/packages/input/stories/input.stories.tsx",
  "packages/layout/stories/aspect-ratio.stories":
    "/Users/morse/Documents/GitHub/chakra-ui/packages/layout/stories/aspect-ratio.stories.tsx",
  "packages/layout/stories/badge.stories":
    "/Users/morse/Documents/GitHub/chakra-ui/packages/layout/stories/badge.stories.tsx",
  "packages/layout/stories/box.stories":
    "/Users/morse/Documents/GitHub/chakra-ui/packages/layout/stories/box.stories.tsx",
  "packages/layout/stories/center.stories":
    "/Users/morse/Documents/GitHub/chakra-ui/packages/layout/stories/center.stories.tsx",
  "packages/layout/stories/code.stories":
    "/Users/morse/Documents/GitHub/chakra-ui/packages/layout/stories/code.stories.tsx",
  "packages/layout/stories/container.stories":
    "/Users/morse/Documents/GitHub/chakra-ui/packages/layout/stories/container.stories.tsx",
  "packages/layout/stories/divider.stories":
    "/Users/morse/Documents/GitHub/chakra-ui/packages/layout/stories/divider.stories.tsx",
  "packages/layout/stories/grid.stories":
    "/Users/morse/Documents/GitHub/chakra-ui/packages/layout/stories/grid.stories.tsx",
  "packages/layout/stories/link.stories":
    "/Users/morse/Documents/GitHub/chakra-ui/packages/layout/stories/link.stories.tsx",
  "packages/layout/stories/list.stories":
    "/Users/morse/Documents/GitHub/chakra-ui/packages/layout/stories/list.stories.tsx",
  "packages/layout/stories/stack.stories":
    "/Users/morse/Documents/GitHub/chakra-ui/packages/layout/stories/stack.stories.tsx",
  "packages/layout/stories/wrap.stories":
    "/Users/morse/Documents/GitHub/chakra-ui/packages/layout/stories/wrap.stories.tsx",
  "packages/live-region/stories/live-region.stories":
    "/Users/morse/Documents/GitHub/chakra-ui/packages/live-region/stories/live-region.stories.tsx",
  "packages/media-query/stories/media-query.stories":
    "/Users/morse/Documents/GitHub/chakra-ui/packages/media-query/stories/media-query.stories.tsx",
  "packages/menu/stories/menu.stories":
    "/Users/morse/Documents/GitHub/chakra-ui/packages/menu/stories/menu.stories.tsx",
  "packages/modal/stories/modal.stories":
    "/Users/morse/Documents/GitHub/chakra-ui/packages/modal/stories/modal.stories.tsx",
  "packages/number-input/stories/number-input.stories":
    "/Users/morse/Documents/GitHub/chakra-ui/packages/number-input/stories/number-input.stories.tsx",
  "packages/parser/stories/parser.stories":
    "/Users/morse/Documents/GitHub/chakra-ui/packages/parser/stories/parser.stories.tsx",
  "packages/pin-input/stories/pin-input.stories":
    "/Users/morse/Documents/GitHub/chakra-ui/packages/pin-input/stories/pin-input.stories.tsx",
  "packages/popover/stories/popover.stories":
    "/Users/morse/Documents/GitHub/chakra-ui/packages/popover/stories/popover.stories.tsx",
  "packages/popper/stories/popper.stories":
    "/Users/morse/Documents/GitHub/chakra-ui/packages/popper/stories/popper.stories.tsx",
  "packages/portal/stories/portal.stories":
    "/Users/morse/Documents/GitHub/chakra-ui/packages/portal/stories/portal.stories.tsx",
  "packages/progress/stories/circular-progress.stories":
    "/Users/morse/Documents/GitHub/chakra-ui/packages/progress/stories/circular-progress.stories.tsx",
  "packages/progress/stories/progress.stories":
    "/Users/morse/Documents/GitHub/chakra-ui/packages/progress/stories/progress.stories.tsx",
  "packages/radio/stories/radio.stories":
    "/Users/morse/Documents/GitHub/chakra-ui/packages/radio/stories/radio.stories.tsx",
  "packages/select/stories/select.stories":
    "/Users/morse/Documents/GitHub/chakra-ui/packages/select/stories/select.stories.tsx",
  "packages/skeleton/stories/skeleton.stories":
    "/Users/morse/Documents/GitHub/chakra-ui/packages/skeleton/stories/skeleton.stories.tsx",
  "packages/skip-nav/stories/skip-nav.stories":
    "/Users/morse/Documents/GitHub/chakra-ui/packages/skip-nav/stories/skip-nav.stories.tsx",
  "packages/slider/stories/slider.stories":
    "/Users/morse/Documents/GitHub/chakra-ui/packages/slider/stories/slider.stories.tsx",
  "packages/spinner/stories/spinner.stories":
    "/Users/morse/Documents/GitHub/chakra-ui/packages/spinner/stories/spinner.stories.tsx",
  "packages/stat/stories/stat.stories":
    "/Users/morse/Documents/GitHub/chakra-ui/packages/stat/stories/stat.stories.tsx",
  "packages/switch/stories/switch.stories":
    "/Users/morse/Documents/GitHub/chakra-ui/packages/switch/stories/switch.stories.tsx",
  "packages/system/stories/system-advanced.stories":
    "/Users/morse/Documents/GitHub/chakra-ui/packages/system/stories/system-advanced.stories.tsx",
  "packages/system/stories/system.stories":
    "/Users/morse/Documents/GitHub/chakra-ui/packages/system/stories/system.stories.tsx",
  "packages/tabs/stories/tabs.stories":
    "/Users/morse/Documents/GitHub/chakra-ui/packages/tabs/stories/tabs.stories.tsx",
  "packages/tag/stories/tag.stories":
    "/Users/morse/Documents/GitHub/chakra-ui/packages/tag/stories/tag.stories.tsx",
  "packages/textarea/stories/textarea.stories":
    "/Users/morse/Documents/GitHub/chakra-ui/packages/textarea/stories/textarea.stories.tsx",
  "packages/toast/stories/toast.stories":
    "/Users/morse/Documents/GitHub/chakra-ui/packages/toast/stories/toast.stories.tsx",
  "packages/tooltip/stories/tooltip.stories":
    "/Users/morse/Documents/GitHub/chakra-ui/packages/tooltip/stories/tooltip.stories.tsx",
  "packages/transition/stories/transition.stories":
    "/Users/morse/Documents/GitHub/chakra-ui/packages/transition/stories/transition.stories.tsx",
  "packages/visually-hidden/stories/visually-hidden.stories":
    "/Users/morse/Documents/GitHub/chakra-ui/packages/visually-hidden/stories/visually-hidden.stories.tsx",
}
